AWSTemplateFormatVersion: "2010-09-09"

Description: Infrastructure stack for MkDocs wiki to be published on S3 / CloudFront

#-------------------------------------------------------------------------------
#--[ PARAMETRES ]---------------------------------------------------------------
#-------------------------------------------------------------------------------

Parameters:
  WebsiteBucket:
    Description: Bucket where the website should be synchronized
    Type: String

  HostedDNSZone:
    Description: DNS zone for the website to be pointed to
    Default: ricebowljr.cc.
    Type: String

#-------------------------------------------------------------------------------
#--[ RESOURCES ]----------------------------------------------------------------
#-------------------------------------------------------------------------------
 
Resources:
#--[ S3 Bucket ]----------------------------------------------------------------
  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      AccessControl: PublicRead
      BucketName: !Ref WebsiteBucket
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    DeletionPolicy: Retain

#--[ Route 53 RR ]--------------------------------------------------------------
  Route53RecordSet:
    Type: "AWS::Route53::RecordSet"
    Properties:
      HostedZoneName: !Ref HostedDNSZone
      Name: !Sub "wiki.${HostedDNSZone}"
      Type: A
      AliasTarget:
        #DNSName: !Ref CloudFrontDistribution
        DNSName: d2egakoj9uwo72.cloudfront.net
        HostedZoneId: Z2FDTNDATAQYW2
      

#-------------------------------------------------------------------------------
#--[ OUTPUTS ]----------------------------------------------------------------
#-------------------------------------------------------------------------------

Outputs:
  WebsiteURL:
    Value: !GetAtt [S3Bucket, WebsiteURL]
    Description: URL for website hosted on S3
  S3BucketSecureURL:
    Value: !Join ['', ['https://', !GetAtt [S3Bucket, DomainName]]]
    Description: Name of S3 bucket to hold website content
